### PR TITLE
Don't overwrite database yml if RDS_URL is set

### PR DESCRIPTION
**Pull request by jooshbzm**
@mtoneil @acreeger does this look right to you? Figure we might as well leave behavior the same unless `RDS_URL` is set.

### CODE REVIEW

**Comment by jooshbzm** [comment]
@mtoneil and I looked at this - merging

**Comment by mtoneil** [comment]
@jooshbzm shouldn't this just always return false?

**Comment by mtoneil** [comment]
I guess it does. But why even do the active record check?

**Comment by jooshbzm** [comment]
I don't really want to screw with anything else - would rather just leave it in there.

**Comment by mtoneil** [comment]
Um ok. But we never want it to overwrite database.yml. Seems easier to understand if the function just does "return false" at the top

**Pull request merged**
